name: Deploy UTI Risk Calculator

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest streamlit
        
    - name: Test application startup
      run: |
        streamlit run app.py --server.headless=true &
        sleep 10
        curl -f http://localhost:8501/ || exit 1
        
    - name: Run basic tests
      run: |
        python -c "import app; print('App imports successfully')"
        python -c "import streamlit as st; print('Streamlit works')"
        
  security-scan:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run security scan
      uses: pypa/gh-action-pip-audit@v1.0.8
      with:
        inputs: requirements.txt
        
  deploy-notification:
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deployment Ready
      run: |
        echo "🚀 Application is ready for deployment!"
        echo "✅ All tests passed"
        echo "🔒 Security scan completed"
        echo "📱 Deploy to Streamlit Cloud: https://share.streamlit.io"
